### PR TITLE
ItemSkiper helper implemented and compatability with connections bundle v0.5.0 added

### LINKED ISSUE #33: Implement new Skipitem helper
Implement new Skipitem helper from connectiions bunde > 0.5.x in sandbox magento branch.
This should stop memory leaks on import and crashes on Sync.

### PR DESCRIPTION
**Pull request by lukasvtechceo**
will close #33

### CODE REVIEW

File: Modifier/CategoryModifier.php [hunk 1]
```diff
@@ -79,7 +79,7 @@ protected function transform(CategoryDocument $document, CatalogCategoryEntity $
             // Root categories.
             $document->setParentId(CategoryDocument::ROOT_ID);
         } elseif ($entity->getLevel() < 2) {
-            throw new ItemSkipException('Wrong category level. Got level=' . $entity->getLevel());
+            ItemSkipper::skip($event, 'Wrong category level. Got level=' . $entity->getLevel());
```
Comment (GrandLTU) [inline Modifier/CategoryModifier.php:82]: Maybe return statement is needed after this?

File: Modifier/ProductModifier.php [hunk 2]
```diff
@@ -85,7 +85,7 @@ protected function transform(ProductDocument $document, CatalogProductEntity $en
             $this->addVarcharAttributes($entity, $document);
             $this->addCategories($entity, $document);
         } else {
-            throw new ItemSkipException('Product ' . $entity->getId() . ' is disabled, so it wont be imported.');
+            ItemSkipper::skip($event, 'Product ' . $entity->getId() . ' is disabled, so it wont be imported.');
```
Comment (GrandLTU) [inline Modifier/ProductModifier.php:78]:
``` php
if (!$this->isProductActive($entity)) {
     ItemSkipper::skip(...);

     return;
}
```

would be clearer IMHO.

File: Tests/Functional/Sync/SyncTest.php [hunk 3]
```diff
@@ -138,8 +142,22 @@ private function getExpectedDocuments()
...
+        $expectedDocument->setScore(1.0);
+        $expectedDocument->setHeading('Heading');
+        $expectedDocument->setSlug('newpage');
+        $expectedDocument->setTitle('NewPageUpdated');
+        $expectedDocument->setContent('<p>Content&nbsp;Updated</p>');
 
+        $id = $expectedDocument->getId();
+        $expectedDocuments['ONGRMagentoConnectorBundle:ContentDocument']['documents'][$id] = $expectedDocument;
+
+        // Product With Category and With Url.
```
Comment (GrandLTU) [inline Tests/Functional/Sync/SyncTest.php]: I don't think that all word needs capitalization.

File: Tests/Functional/Sync/SyncTest.php [hunk 4]
```diff
@@ -158,8 +176,10 @@ private function getExpectedDocuments()
         $expectedDocument->addImageUrl('no_selection');
         $expectedDocument->addSmallImageUrl('no_selection');
 
-        $expectedDocuments['ONGRMagentoConnectorBundle:ProductDocument']['documents'][] = $expectedDocument;
+        $id = $expectedDocument->getId();
+        $expectedDocuments['ONGRMagentoConnectorBundle:ProductDocument']['documents'][$id] = $expectedDocument;
 
+        // Product With Category With Url.
```
Comment (GrandLTU) [inline Tests/Functional/Sync/SyncTest.php]: Comment is kinda the same as previous.
